modified:   .github/workflows/qa_val.yml

diff --git a/.github/workflows/qa_val.yml b/.github/workflows/qa_val.yml
--- a/.github/workflows/qa_val.yml
+++ b/.github/workflows/qa_val.yml
@@ -61,98 +61,90 @@ jobs:
         run: |
           python -m pip install --upgrade pip wheel
           pip install -e ".[dev]"
-      # Testing ----------------------------
-      # Check DATABRICKS_HOST
-      - name: Check DATABRICKS_HOST host resolves
-        run: |
-          if [[ ! "$DATABRICKS_HOST" =~ ^https?:// ]]; then
-            echo "Error: DATABRICKS_HOST must start with http:// or https://"
-            exit 1
-          fi
-          curl -Is --fail "$DATABRICKS_HOST" || { echo "❌ Host not reachable"; exit 1; }
-          echo "✅ Host is reachable"
+      # # Testing ----------------------------
+      # # Check DATABRICKS_HOST
+      # - name: Check DATABRICKS_HOST host resolves
+      #   run: |
+      #     if [[ ! "$DATABRICKS_HOST" =~ ^https?:// ]]; then
+      #       echo "Error: DATABRICKS_HOST must start with http:// or https://"
+      #       exit 1
+      #     fi
+      #     curl -Is --fail "$DATABRICKS_HOST" || { echo "❌ Host not reachable"; exit 1; }
+      #     echo "✅ Host is reachable"
       
-      # Check DATABRICKS_TOKEN
-      - name: Check DATABRICKS_TOKEN authentication
-        run: |
-          response=$(curl -s -o /dev/null -w "%{http_code}" \
-            -H "Authorization: Bearer $DATABRICKS_TOKEN" \
-            "$DATABRICKS_HOST/api/2.0/clusters/list")
+      # # Check DATABRICKS_TOKEN
+      # - name: Check DATABRICKS_TOKEN authentication
+      #   run: |
+      #     response=$(curl -s -o /dev/null -w "%{http_code}" \
+      #       -H "Authorization: Bearer $DATABRICKS_TOKEN" \
+      #       "$DATABRICKS_HOST/api/2.0/clusters/list")
 
-          if [ "$response" -eq 200 ]; then
-            echo "✅ DATABRICKS_TOKEN is valid."
-          elif [ "$response" -eq 401 ]; then
-            echo "❌ Unauthorized: DATABRICKS_TOKEN is invalid or expired."
-            exit 1
-          else
-            echo "⚠️ Unexpected response code: $response"
-            exit 1
-          fi
+      #     if [ "$response" -eq 200 ]; then
+      #       echo "✅ DATABRICKS_TOKEN is valid."
+      #     elif [ "$response" -eq 401 ]; then
+      #       echo "❌ Unauthorized: DATABRICKS_TOKEN is invalid or expired."
+      #       exit 1
+      #     else
+      #       echo "⚠️ Unexpected response code: $response"
+      #       exit 1
+      #     fi
 
-      # Check GH_TOKEN
-      - name: Check GH_TOKEN authentication
-        run: |
-          user=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/user | jq -r '.login')
-          if [ "$user" = "null" ] || [ -z "$user" ]; then
-            echo "❌ GH_TOKEN invalid or expired."
-            exit 1
-          else
-            echo "✅ Authenticated as: $user"
-          fi
-      # Check GH_TOKEN User
-      - name: Check GitHub user
-        run: |
-          curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/user | jq
+      # # Check GH_TOKEN
+      # - name: Check GH_TOKEN authentication
+      #   run: |
+      #     user=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/user | jq -r '.login')
+      #     if [ "$user" = "null" ] || [ -z "$user" ]; then
+      #       echo "❌ GH_TOKEN invalid or expired."
+      #       exit 1
+      #     else
+      #       echo "✅ Authenticated as: $user"
+      #     fi
+      # # Check GH_TOKEN User
+      # - name: Check GitHub user
+      #   run: |
+      #     curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/user | jq
       
-      - name: Check if secrets are available
-        run: |
-          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
-            echo "Secrets not set properly. ${{ secrets.GH_TOKEN }} "
-            exit 1
-          else
-            echo "Secrets are set"
-          fi
-      # Testing ----------------------------
-      - name: Upload config file to Unity Catalog Volume (overwrite-safe)
-        run: |
-          set -e
-          file_path="/Volumes/data_lake_dev/feature_config/volume/data_pipeline_config_dev.json"
+      # - name: Check if secrets are available
+      #   run: |
+      #     if [ -z "${{ secrets.GH_TOKEN }}" ]; then
+      #       echo "Secrets not set properly. ${{ secrets.GH_TOKEN }} "
+      #       exit 1
+      #     else
+      #       echo "Secrets are set"
+      #     fi
+      # # Testing ----------------------------
+      # - name: Upload config file to Unity Catalog Volume (overwrite-safe)
+      #   run: |
+      #     set -e
+      #     file_path="/Volumes/data_lake_dev/feature_config/volume/data_pipeline_config_dev.json"
 
-          echo "🧹 Deleting existing file if present..."
-          curl -s -X DELETE -H "Authorization: Bearer $DATABRICKS_TOKEN" \
-            "$DATABRICKS_HOST/api/2.1/unity-catalog/volumes/files/delete?path=${file_path}" || true
+      #     echo "🧹 Deleting existing file if present..."
+      #     curl -s -X DELETE -H "Authorization: Bearer $DATABRICKS_TOKEN" \
+      #       "$DATABRICKS_HOST/api/2.1/unity-catalog/volumes/files/delete?path=${file_path}" || true
 
-          echo "⬆️ Uploading configuration file..."
-          status=$(curl -s -o /dev/null -w "%{http_code}" \
-            -X POST -H "Authorization: Bearer $DATABRICKS_TOKEN" \
-            -F path="${file_path}" \
-            -F contents=@data_pipeline/core/config/data_pipeline_config_dev.json \
-            "$DATABRICKS_HOST/api/2.1/unity-catalog/volumes/files/upload")
+      #     echo "⬆️ Uploading configuration file..."
+      #     status=$(curl -s -o /dev/null -w "%{http_code}" \
+      #       -X POST -H "Authorization: Bearer $DATABRICKS_TOKEN" \
+      #       -F path="${file_path}" \
+      #       -F contents=@data_pipeline/core/config/data_pipeline_config_dev.json \
+      #       "$DATABRICKS_HOST/api/2.1/unity-catalog/volumes/files/upload")
 
-          if [ "$status" -eq 200 ]; then
-            echo "✅ File uploaded successfully to ${file_path}"
-          else
-            echo "❌ Upload failed with status code: $status"
-            exit 1
-          fi
+      #     if [ "$status" -eq 200 ]; then
+      #       echo "✅ File uploaded successfully to ${file_path}"
+      #     else
+      #       echo "❌ Upload failed with status code: $status"
+      #       exit 1
+      #     fi
 
-        # databricks fs cp --overwrite data_pipeline/core/config/data_pipeline_config_dev.json /Volumes/data_lake_dev/feature_config/volume/data_pipeline_config_dev.json
-
-
+      #   # databricks fs cp --overwrite data_pipeline/core/config/data_pipeline_config_dev.json /Volumes/data_lake_dev/feature_config/volume/data_pipeline_config_dev.json
 
 
 
-      - name: Deploy Integration test suite other than ddp
-        if: ${{ inputs.job_type != 'ddp' }}
+
+
+      - name: Deploy Integration Test Suite
         run: |
           dbx deploy --job=we-pipeline-${{ inputs.job_type }}-${{ inputs.test_type }}-${{ inputs.environment }}-${{ inputs.space }}-val-v1 --deployment-file=${{ inputs.deployment_file }} --environment ${{ inputs.environment }}_${{ inputs.space }} --debug
-
-      # - name: Deploy Integration test suite ddp
-      #   if: ${{ inputs.job_type == 'ddp' }}
-      #   run: |
-      #     dbx deploy --job=ddp-val-wf --deployment-file=${{ inputs.deployment_file }} --environment ${{ inputs.environment }}_${{ inputs.space }} --debug
-
-      # - name: Run Integration test suite for cross_platform_count
-      #   if: ${{ inputs.job_type == 'cross_platform_count' }}
-      #   run: |
-      #       dbx launch --job=we-pipeline-${{ inputs.job_type }}-${{ inputs.test_type }}-${{ inputs.environment }}-${{ inputs.space }}-val-v1 --trace --environment ${{ inputs.environment }}_${{ inputs.space }} --parameters='{"python_params": ["we.pipeline.validation.task.${{ inputs.job_type }}_val", "--env", "'${{ inputs.environment }}'", "--space", "'${{ inputs.space }}'", "--object_type", "'${{ inputs.object_type }}'", "--job_type", "'${{ inputs.job_type }}'", "--test_type", "'${{ inputs.test_type }}'"]}'
+      - name: Run Integration test suite for cross_platform_count
+        run: |
+            dbx launch --job=we-pipeline-${{ inputs.job_type }}-${{ inputs.test_type }}-${{ inputs.environment }}-${{ inputs.space }}-val-v1 --trace --environment ${{ inputs.environment }}_${{ inputs.space }} --parameters='{"python_params": ["we.pipeline.validation.task.${{ inputs.job_type }}_val", "--env", "'${{ inputs.environment }}'", "--space", "'${{ inputs.space }}'", "--object_type", "'${{ inputs.object_type }}'", "--job_type", "'${{ inputs.job_type }}'", "--test_type", "'${{ inputs.test_type }}'"]}'
